//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_codes
    {
        public coupon_codes()
        {
            this.products = new HashSet<product>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public long coupon_type { get; set; }
        public Nullable<decimal> deduct { get; set; }
    
        public virtual coupon_type coupon_type1 { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
