//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_type
    {
        public coupon_type()
        {
            this.coupon_codes = new HashSet<coupon_codes>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<coupon_codes> coupon_codes { get; set; }
    }
}
