//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.order_product = new HashSet<order_product>();
        }
    
        public long id { get; set; }
        public long order_no { get; set; }
        public long user_id { get; set; }
        public Nullable<bool> is_Guest { get; set; }
        public string address { get; set; }
        public string card_name { get; set; }
        public string card_number { get; set; }
        public Nullable<decimal> card_cvv { get; set; }
        public Nullable<int> card_expiration_month { get; set; }
        public Nullable<int> card_expiration_year { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> taxes { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual ICollection<order_product> order_product { get; set; }
        public virtual user user { get; set; }
    }
}
