//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_product
    {
        public long id { get; set; }
        public Nullable<long> order_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
