//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.order_product = new HashSet<order_product>();
        }
    
        public long id { get; set; }
        public long category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<long> coupon_id { get; set; }
        public string image { get; set; }
    
        public virtual coupon_codes coupon_codes { get; set; }
        public virtual ICollection<order_product> order_product { get; set; }
        public virtual product_category product_category { get; set; }
    }
}
