//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_category
    {
        public product_category()
        {
            this.products = new HashSet<product>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
